# Generated by Django 6.0.7 on 2026-07-16 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ramalhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('missa_comunhao', models.IntegerField()),
                ('visita_ao_santissimo', models.IntegerField()),
                ('tercos', models.IntegerField()),
                ('exame_de_consciencia', models.IntegerField()),
                ('leitura_espiritual_meditacao', models.IntegerField()),
                ('sacrificio', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
