# Generated by Django 6.0.7 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DELETE FROM app_ramalhete
                WHERE id NOT IN (
                    SELECT MIN(id)
                    FROM app_ramalhete
                    GROUP BY usuario_id, date(data)
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="UPDATE app_ramalhete SET data = date(data);",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='ramalhete',
            name='data',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='ramalhete',
            constraint=models.UniqueConstraint(fields=('usuario', 'data'), name='unique_ramalhete_por_usuario_data'),
        ),
    ]
